# Generated by Django 4.2.7 on 2026-01-27 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_users', models.PositiveSmallIntegerField(default=100)),
                ('price', models.PositiveIntegerField(default=5000)),
                ('start_message', models.TextField(default='Start message')),
                ('merchant_message', models.TextField(default='Merchants')),
                ('ceo_message', models.TextField(default='CEOs')),
                ('end_of_registration', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядковый номер')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('field_type', models.CharField(choices=[('text', 'Текст'), ('email', 'Email'), ('phone', 'Телефон'), ('fullname', 'ФИО'), ('date', 'Дата')], max_length=20, verbose_name='Тип поля')),
                ('field_name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Имя поля')),
                ('error_message', models.TextField(default='Некорректные данные', verbose_name='Текст ошибки')),
                ('next_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_steps', to='bot.registrationstep', verbose_name='Следующий шаг')),
            ],
            options={
                'verbose_name': 'Шаг регистрации',
                'verbose_name_plural': 'Шаги регистрации',
            },
        ),
    ]
