# Generated by Django 4.2.7 on 2026-02-02 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configuration",
            options={
                "verbose_name": "Конфигурация бота",
                "verbose_name_plural": "Конфигурация бота",
            },
        ),
        migrations.AddField(
            model_name="configuration",
            name="already_registered_message",
            field=models.TextField(default="Already registered"),
        ),
        migrations.AddField(
            model_name="configuration",
            name="closed_registrations_message",
            field=models.TextField(default="Registrations are closed"),
        ),
        migrations.AddField(
            model_name="configuration",
            name="format_message",
            field=models.TextField(default="Format message"),
        ),
        migrations.AddField(
            model_name="configuration",
            name="invoice_description",
            field=models.CharField(default="Описание регистрации", max_length=100),
        ),
        migrations.AddField(
            model_name="configuration",
            name="invoice_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="invoices/",
                verbose_name="Фото инвойса",
            ),
        ),
        migrations.AddField(
            model_name="configuration",
            name="invoice_label",
            field=models.CharField(
                default="Регистрация на мероприятие", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="configuration",
            name="invoice_title",
            field=models.CharField(
                default="Регистрация на мероприятие", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="end_of_registration",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=1000,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(69),
                    django.core.validators.MaxValueValidator(15000),
                ],
                verbose_name="Цена в рублях",
            ),
        ),
    ]
