# Generated by Django 4.2.7 on 2026-02-02 14:00

from django.db import migrations


def create_config(apps, schema_editor):
    Configuration = apps.get_model('bot', 'Configuration')
    Configuration.objects.get_or_create(id=1)

class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0002_alter_configuration_options_and_more'),
    ]
    operations = [
        migrations.RunPython(create_config, migrations.RunPython.noop),
    ]