# Generated by Django 4.2.7 on 2026-01-27 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(help_text='pendant, cap, shirt и т.д.', max_length=100, unique=True, verbose_name='Внутреннее имя')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Количество на складе')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('label', models.CharField(max_length=255, verbose_name='Название для платежа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в рублях')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен ли товар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-available', 'good_name'],
            },
        ),
        migrations.CreateModel(
            name='GoodPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='goods/')),
                ('is_invoice', models.BooleanField(default=False, help_text='Если ни одно не отмечено, используется первое из предоставленных', verbose_name='Фото в оплате')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='goods.good', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фотографии товара',
            },
        ),
    ]
