# Generated by Django 4.2.7 on 2026-02-02 14:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='goods/')),
                ('is_invoice', models.BooleanField(default=False, help_text='Если ни одно не отмечено, используется первое из предоставленных', verbose_name='Фото в оплате')),
                ('telegram_file_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фотографии товара',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ['-available'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='good',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='good',
            name='good_name',
        ),
        migrations.RemoveField(
            model_name='good',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(69), django.core.validators.MaxValueValidator(15000)], verbose_name='Цена в рублях'),
        ),
        migrations.AlterField(
            model_name='good',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Название товара'),
        ),
        migrations.DeleteModel(
            name='GoodPhoto',
        ),
        migrations.AddField(
            model_name='order',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='goods.good', verbose_name='Заказы'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказы'),
        ),
        migrations.AddField(
            model_name='goodimage',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.good', verbose_name='Товар'),
        ),
    ]
