# Generated by Django 4.2.7 on 2026-02-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodimage_order_alter_good_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodimage',
            name='hash',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
    ]
