# Generated by Django 4.2.7 on 2026-01-27 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название рассылки')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('both', 'Email + Telegram')], default='both', max_length=20, verbose_name='Канал доставки')),
                ('only_paid', models.BooleanField(default=False, verbose_name='Только оплатившие')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирована'), ('sending', 'Отправляется'), ('sent', 'Отправлена'), ('failed', 'Ошибка'), ('partial', 'Частично отправлена')], default='draft', max_length=20, verbose_name='Статус')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Запланирована на')),
                ('total_recipients', models.IntegerField(default=0, verbose_name='Всего получателей')),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='newsletters/')),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterMainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Фотография баннера')),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='NewsletterTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('channel_sent', models.CharField(blank=True, choices=[('email', 'Email'), ('telegram', 'Telegram'), ('both', 'Email + Telegram')], max_length=20, null=True, verbose_name='Через какой канал отправлено')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='newsletters.newsletter', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Задача рассылки',
                'verbose_name_plural': 'Задачи рассылок',
                'ordering': ['-created_at'],
            },
        ),
    ]
