# Generated by Django 4.2.7 on 2026-02-02 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterMainBanner',
        ),
        migrations.AlterModelOptions(
            name='newslettertask',
            options={'ordering': ['channel_sent'], 'verbose_name': 'Задача рассылки', 'verbose_name_plural': 'Задачи рассылок'},
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='total_recipients',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='failed_count',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='sent_count',
        ),
        migrations.AddField(
            model_name='newsletterimage',
            name='newsletter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='newsletters.newsletter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletterimage',
            name='telegram_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newslettertask',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланирована'), ('sending', 'Отправляется'), ('sent', 'Отправлена'), ('failed', 'Ошибка'), ('partial', 'Частично отправлена')], default='sending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='newslettertask',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterUniqueTogether(
            name='newslettertask',
            unique_together={('newsletter', 'user')},
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['status', 'scheduled_at'], name='newsletters_status_930d15_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettertask',
            index=models.Index(fields=['newsletter', 'channel_sent'], name='newsletters_newslet_c8c6e1_idx'),
        ),
    ]
